import type { AxisValues } from "./axes";

export type DomainId =
  | "hiring"
  | "onboarding"
  | "goals"
  | "comp"
  | "performance"
  | "tools";

export type RoleId = "employee" | "manager" | "pro";

/** What the retrofit actually lands on — 95% of these screens already exist. */
export type SurfaceId =
  | "table"
  | "form"
  | "blank"
  | "catalog"
  | "navigation"
  | "calendar"
  | "document";

export const domains: Record<DomainId, { name: string; color: string }> = {
  hiring: { name: "Найм", color: "oklch(0.73 0.15 32)" },
  onboarding: { name: "Адаптация", color: "oklch(0.80 0.13 95)" },
  goals: { name: "Цели и ресурсы", color: "oklch(0.74 0.14 150)" },
  comp: { name: "Мотивация и C&B", color: "oklch(0.76 0.12 200)" },
  performance: { name: "Перформанс", color: "oklch(0.71 0.14 288)" },
  tools: { name: "Рабочие инструменты", color: "oklch(0.75 0.13 330)" },
};

export const roles: Record<
  RoleId,
  { name: string; short: string; headcount: number; note: string }
> = {
  employee: {
    name: "Сотрудник",
    short: "сотрудник",
    headcount: 30000,
    note: "Приходит редко и вслепую. Налог платит объёмом популяции, а не частотой.",
  },
  manager: {
    name: "Руководитель",
    short: "руководитель",
    headcount: 3600,
    note: "Платит веерностью: одно и то же по каждому подчинённому.",
  },
  pro: {
    name: "HR- и C&B-аналитик",
    short: "аналитик",
    headcount: 150,
    note: "Для него это основной инструмент. Экономия на частоте, а не на популяции.",
  },
};

export const surfaces: Record<SurfaceId, string> = {
  table: "таблица с фильтрами",
  form: "форма",
  blank: "чистый лист",
  catalog: "каталог с правилами",
  navigation: "навигация по порталу",
  calendar: "календарь",
  document: "документ на подпись",
};

export interface Scenario {
  id: string;
  name: string;
  domain: DomainId;
  role: RoleId;
  surface: SurfaceId;
  /** What hurts today, in one line a PM would recognise. */
  pain: string;
  /** Share of the role that actually performs this at all. */
  populationShare: number;
  runsPerYear: number;
  minutesPerRun: number;
  /** Share of the step's minutes a language mechanic can realistically remove. */
  removableShare: number;
  /** Drawn on the navigation frame rather than inside the plane. */
  meta?: boolean;
  values: AxisValues;
}

const v = (values: AxisValues) => values;

export const scenarios: Scenario[] = [
  {
    id: "cand-search",
    name: "Поиск кандидатов под требования",
    domain: "hiring",
    role: "pro",
    surface: "table",
    pain: "Требования формулируются словами, а ищутся двадцатью фильтрами, которые приходится подбирать наугад.",
    populationShare: 1,
    runsPerYear: 400,
    minutesPerRun: 25,
    removableShare: 0.45,
    values: v({
      openness: 0.9,
      mode: 0.25,
      initiative: 0.1,
      temporality: 0.25,
      delegation: 0.2,
      expertise: 0.9,
      stake: 0.15,
      trust: 0.35,
      attention: 0.3,
      cardinality: 0.55,
      precision: 0.2,
      formStability: 0.9,
    }),
  },
  {
    id: "interview-schedule",
    name: "Согласование слотов интервью",
    domain: "hiring",
    role: "pro",
    surface: "calendar",
    pain: "Пересечь календари четырёх интервьюеров и кандидата вручную — это переписка на полдня.",
    populationShare: 1,
    runsPerYear: 300,
    minutesPerRun: 12,
    removableShare: 0.6,
    values: v({
      openness: 0.4,
      mode: 0.8,
      initiative: 0.35,
      temporality: 0.85,
      delegation: 0.75,
      expertise: 0.8,
      stake: 0.35,
      trust: 0.3,
      attention: 0.55,
      cardinality: 0.75,
      precision: 0.3,
      formStability: 0.8,
    }),
  },
  {
    id: "interview-feedback",
    name: "Фидбек после интервью",
    domain: "hiring",
    role: "manager",
    surface: "form",
    pain: "Заметки уже написаны в блокноте, но форму с шестью критериями надо заполнить заново руками.",
    populationShare: 0.6,
    runsPerYear: 20,
    minutesPerRun: 20,
    removableShare: 0.45,
    values: v({
      openness: 0.7,
      mode: 0.85,
      initiative: 0.45,
      temporality: 0.2,
      delegation: 0.25,
      expertise: 0.45,
      stake: 0.55,
      trust: 0.45,
      attention: 0.45,
      cardinality: 0.25,
      precision: 0.25,
      formStability: 0.55,
    }),
  },
  {
    id: "offer-approve",
    name: "Согласование оффера",
    domain: "hiring",
    role: "manager",
    surface: "form",
    pain: "Проверка вилки, грейда и бюджета руками, а цена ошибки — отозванный оффер.",
    populationShare: 0.5,
    runsPerYear: 6,
    minutesPerRun: 15,
    removableShare: 0.35,
    values: v({
      openness: 0.2,
      mode: 0.9,
      initiative: 0.5,
      temporality: 0.45,
      delegation: 0.35,
      expertise: 0.55,
      stake: 0.9,
      trust: 0.75,
      attention: 0.55,
      cardinality: 0.4,
      precision: 0.55,
      formStability: 0.9,
    }),
  },
  {
    id: "wiki-answer",
    name: "Найти ответ в вики и базе знаний",
    domain: "onboarding",
    role: "employee",
    surface: "navigation",
    pain: "Ответ в системе есть, но человек не знает слова, которым он там назван.",
    populationShare: 0.9,
    runsPerYear: 40,
    minutesPerRun: 6,
    removableShare: 0.5,
    values: v({
      openness: 0.85,
      mode: 0.15,
      initiative: 0.05,
      temporality: 0.1,
      delegation: 0.1,
      expertise: 0.25,
      stake: 0.1,
      trust: 0.2,
      attention: 0.35,
      cardinality: 0.1,
      precision: 0.1,
      formStability: 0.3,
    }),
  },
  {
    id: "probation-checklist",
    name: "Чеклист испытательного срока",
    domain: "onboarding",
    role: "employee",
    surface: "table",
    pain: "Список фиксированный и короткий. Проблема не в вводе, а в том, что о нём забывают.",
    populationShare: 0.15,
    runsPerYear: 12,
    minutesPerRun: 5,
    removableShare: 0.2,
    values: v({
      openness: 0.1,
      mode: 0.55,
      initiative: 0.8,
      temporality: 0.3,
      delegation: 0.15,
      expertise: 0.1,
      stake: 0.4,
      trust: 0.15,
      attention: 0.6,
      cardinality: 0.2,
      precision: 0.35,
      formStability: 0.9,
    }),
  },
  {
    id: "course-pick",
    name: "Подобрать обучающий курс",
    domain: "onboarding",
    role: "employee",
    surface: "catalog",
    pain: "Человек знает свой пробел, но не знает, как курс называется в каталоге.",
    populationShare: 0.5,
    runsPerYear: 3,
    minutesPerRun: 20,
    removableShare: 0.5,
    values: v({
      openness: 0.7,
      mode: 0.45,
      initiative: 0.25,
      temporality: 0.2,
      delegation: 0.15,
      expertise: 0.15,
      stake: 0.15,
      trust: 0.2,
      attention: 0.25,
      cardinality: 0.15,
      precision: 0.15,
      formStability: 0.6,
    }),
  },
  {
    id: "write-goals",
    name: "Написать цели на период",
    domain: "goals",
    role: "employee",
    surface: "blank",
    pain: "Чистый лист раз в полгода. Всё, что нужно для черновика, уже лежит в задачах и прошлых целях.",
    populationShare: 0.95,
    runsPerYear: 2,
    minutesPerRun: 60,
    removableShare: 0.45,
    values: v({
      openness: 0.85,
      mode: 0.85,
      initiative: 0.6,
      temporality: 0.25,
      delegation: 0.3,
      expertise: 0.3,
      stake: 0.35,
      trust: 0.25,
      attention: 0.45,
      cardinality: 0.15,
      precision: 0.15,
      formStability: 0.25,
    }),
  },
  {
    id: "cascade-goals",
    name: "Каскадировать цели на команду",
    domain: "goals",
    role: "manager",
    surface: "table",
    pain: "Одна и та же логика разносится по пятнадцати карточкам подчинённых вручную.",
    populationShare: 1,
    runsPerYear: 2,
    minutesPerRun: 90,
    removableShare: 0.5,
    values: v({
      openness: 0.6,
      mode: 0.85,
      initiative: 0.55,
      temporality: 0.4,
      delegation: 0.7,
      expertise: 0.6,
      stake: 0.45,
      trust: 0.35,
      attention: 0.4,
      cardinality: 0.85,
      precision: 0.3,
      formStability: 0.85,
    }),
  },
  {
    id: "project-setup",
    name: "Создать проект и собрать команду",
    domain: "goals",
    role: "manager",
    surface: "form",
    pain: "Форма на тридцать полей, половина из которых нерелевантна конкретному типу проекта.",
    populationShare: 0.4,
    runsPerYear: 4,
    minutesPerRun: 35,
    removableShare: 0.45,
    values: v({
      openness: 0.7,
      mode: 0.85,
      initiative: 0.15,
      temporality: 0.35,
      delegation: 0.5,
      expertise: 0.5,
      stake: 0.45,
      trust: 0.35,
      attention: 0.3,
      cardinality: 0.6,
      precision: 0.3,
      formStability: 0.7,
    }),
  },
  {
    id: "resource-plan",
    name: "Планирование аллокаций",
    domain: "goals",
    role: "pro",
    surface: "table",
    pain: "Каждый вопрос «а что если» требует новой выгрузки и пересборки сводной.",
    populationShare: 1,
    runsPerYear: 120,
    minutesPerRun: 40,
    removableShare: 0.4,
    values: v({
      openness: 0.8,
      mode: 0.6,
      initiative: 0.2,
      temporality: 0.35,
      delegation: 0.4,
      expertise: 0.9,
      stake: 0.55,
      trust: 0.4,
      attention: 0.4,
      cardinality: 0.7,
      precision: 0.4,
      formStability: 0.95,
    }),
  },
  {
    id: "comp-explain",
    name: "Разобраться в составе зарплаты",
    domain: "comp",
    role: "employee",
    surface: "table",
    pain: "Цифры на экране есть, объяснения нет — и человек идёт с этим вопросом в HR.",
    populationShare: 0.8,
    runsPerYear: 6,
    minutesPerRun: 12,
    removableShare: 0.45,
    values: v({
      openness: 0.35,
      mode: 0.1,
      initiative: 0.15,
      temporality: 0.1,
      delegation: 0.05,
      expertise: 0.1,
      stake: 0.3,
      trust: 0.75,
      attention: 0.4,
      cardinality: 0.1,
      precision: 0.2,
      formStability: 0.95,
    }),
  },
  {
    id: "benefit-pick",
    name: "Выбрать бенефит из каталога",
    domain: "comp",
    role: "employee",
    surface: "catalog",
    pain: "Правила выбора зависят от грейда, стажа и региона, и человек не знает, что ему вообще доступно.",
    populationShare: 0.7,
    runsPerYear: 2,
    minutesPerRun: 30,
    removableShare: 0.5,
    values: v({
      openness: 0.6,
      mode: 0.7,
      initiative: 0.2,
      temporality: 0.25,
      delegation: 0.15,
      expertise: 0.1,
      stake: 0.35,
      trust: 0.5,
      attention: 0.3,
      cardinality: 0.15,
      precision: 0.25,
      formStability: 0.65,
    }),
  },
  {
    id: "loan-apply",
    name: "Оформить денежный заём",
    domain: "comp",
    role: "employee",
    surface: "form",
    pain: "Редкая форма с юридическими последствиями: человек проходит её первый и единственный раз.",
    populationShare: 0.05,
    runsPerYear: 1,
    minutesPerRun: 35,
    removableShare: 0.4,
    values: v({
      openness: 0.25,
      mode: 0.9,
      initiative: 0.1,
      temporality: 0.4,
      delegation: 0.2,
      expertise: 0.05,
      stake: 0.85,
      trust: 0.8,
      attention: 0.45,
      cardinality: 0.2,
      precision: 0.45,
      formStability: 0.9,
    }),
  },
  {
    id: "merit-allocate",
    name: "Распределить бюджет повышений",
    domain: "comp",
    role: "manager",
    surface: "table",
    pain: "Политику руководитель формулирует одной фразой, а исполняет её вручную по каждой строке в рамках бюджета.",
    populationShare: 1,
    runsPerYear: 2,
    minutesPerRun: 120,
    removableShare: 0.4,
    values: v({
      openness: 0.55,
      mode: 0.85,
      initiative: 0.55,
      temporality: 0.35,
      delegation: 0.8,
      expertise: 0.65,
      stake: 0.9,
      trust: 0.85,
      attention: 0.5,
      cardinality: 0.85,
      precision: 0.45,
      formStability: 0.95,
    }),
  },
  {
    id: "comp-modeling",
    name: "Смоделировать пересмотр окладов",
    domain: "comp",
    role: "pro",
    surface: "table",
    pain: "Сценарии считаются выгрузкой в Excel, потому что в интерфейсе нет способа задать гипотезу.",
    populationShare: 1,
    runsPerYear: 30,
    minutesPerRun: 180,
    removableShare: 0.5,
    values: v({
      openness: 0.9,
      mode: 0.4,
      initiative: 0.1,
      temporality: 0.3,
      delegation: 0.35,
      expertise: 0.95,
      stake: 0.45,
      trust: 0.7,
      attention: 0.35,
      cardinality: 0.6,
      precision: 0.35,
      formStability: 0.95,
    }),
  },
  {
    id: "self-review",
    name: "Написать самоотзыв",
    domain: "performance",
    role: "employee",
    surface: "blank",
    pain: "Чистый лист про полгода собственной работы, все факты для которого уже есть в задачах и целях.",
    populationShare: 0.95,
    runsPerYear: 2,
    minutesPerRun: 90,
    removableShare: 0.5,
    values: v({
      openness: 0.85,
      mode: 0.85,
      initiative: 0.7,
      temporality: 0.25,
      delegation: 0.25,
      expertise: 0.25,
      stake: 0.4,
      trust: 0.3,
      attention: 0.55,
      cardinality: 0.1,
      precision: 0.15,
      formStability: 0.2,
    }),
  },
  {
    id: "peer-review",
    name: "Написать отзывы на коллег",
    domain: "performance",
    role: "employee",
    surface: "blank",
    pain: "Шесть чистых листов подряд в дедлайн, и качество падает к третьему.",
    populationShare: 0.9,
    runsPerYear: 6,
    minutesPerRun: 25,
    removableShare: 0.5,
    values: v({
      openness: 0.8,
      mode: 0.85,
      initiative: 0.75,
      temporality: 0.3,
      delegation: 0.3,
      expertise: 0.25,
      stake: 0.45,
      trust: 0.45,
      attention: 0.55,
      cardinality: 0.55,
      precision: 0.2,
      formStability: 0.3,
    }),
  },
  {
    id: "calibration-prep",
    name: "Собрать данные к калибровке",
    domain: "performance",
    role: "manager",
    surface: "table",
    pain: "Сводка по команде собирается руками из четырёх систем, каждый раз заново.",
    populationShare: 1,
    runsPerYear: 2,
    minutesPerRun: 100,
    removableShare: 0.55,
    values: v({
      openness: 0.6,
      mode: 0.45,
      initiative: 0.4,
      temporality: 0.9,
      delegation: 0.7,
      expertise: 0.7,
      stake: 0.55,
      trust: 0.6,
      attention: 0.4,
      cardinality: 0.8,
      precision: 0.25,
      formStability: 0.9,
    }),
  },
  {
    id: "calibration-session",
    name: "Провести калибровку в группе",
    domain: "performance",
    role: "manager",
    surface: "table",
    pain: "Живое обсуждение с конфликтом интересов сторон. Скорость ввода тут вообще не узкое место.",
    populationShare: 1,
    runsPerYear: 2,
    minutesPerRun: 180,
    removableShare: 0.2,
    values: v({
      openness: 0.45,
      mode: 0.7,
      initiative: 0.55,
      temporality: 0.05,
      delegation: 0.45,
      expertise: 0.75,
      stake: 0.85,
      trust: 0.85,
      attention: 0.7,
      cardinality: 0.95,
      precision: 0.55,
      formStability: 0.95,
    }),
  },
  {
    id: "intranet-nav",
    name: "Найти нужный раздел интранета",
    domain: "tools",
    role: "employee",
    surface: "navigation",
    pain: "Полсотни систем под одним зонтиком. Человек знает, что хочет сделать, но не знает, где это живёт.",
    populationShare: 1,
    runsPerYear: 60,
    minutesPerRun: 2.5,
    removableShare: 0.6,
    meta: true,
    values: v({
      openness: 0.8,
      mode: 0.45,
      initiative: 0.0,
      temporality: 0.0,
      delegation: 0.05,
      expertise: 0.3,
      stake: 0.1,
      trust: 0.1,
      attention: 0.25,
      cardinality: 0.05,
      precision: 0.1,
      formStability: 0.4,
    }),
  },
  {
    id: "task-create",
    name: "Поставить задачу в трекер",
    domain: "tools",
    role: "employee",
    surface: "form",
    pain: "Мысль формулируется одной строкой, а раскладывается по восьми обязательным полям.",
    populationShare: 0.6,
    runsPerYear: 40,
    minutesPerRun: 3,
    removableShare: 0.5,
    values: v({
      openness: 0.55,
      mode: 0.85,
      initiative: 0.1,
      temporality: 0.15,
      delegation: 0.2,
      expertise: 0.55,
      stake: 0.15,
      trust: 0.15,
      attention: 0.35,
      cardinality: 0.25,
      precision: 0.2,
      formStability: 0.85,
    }),
  },
  {
    id: "meeting-slot",
    name: "Найти окно и собрать встречу",
    domain: "tools",
    role: "employee",
    surface: "calendar",
    pain: "Условие формулируется фразой, а решается ручным перебором чужих календарей.",
    populationShare: 0.7,
    runsPerYear: 30,
    minutesPerRun: 4,
    removableShare: 0.55,
    values: v({
      openness: 0.45,
      mode: 0.85,
      initiative: 0.1,
      temporality: 0.55,
      delegation: 0.55,
      expertise: 0.4,
      stake: 0.2,
      trust: 0.2,
      attention: 0.45,
      cardinality: 0.6,
      precision: 0.35,
      formStability: 0.85,
    }),
  },
  {
    id: "sign-docs",
    name: "Подписать кадровые документы",
    domain: "tools",
    role: "employee",
    surface: "document",
    pain: "Юридически значимое действие. Ускорять надо доставку и напоминание, а не формулировку намерения.",
    populationShare: 1,
    runsPerYear: 8,
    minutesPerRun: 4,
    removableShare: 0.25,
    values: v({
      openness: 0.1,
      mode: 0.9,
      initiative: 0.75,
      temporality: 0.25,
      delegation: 0.1,
      expertise: 0.05,
      stake: 0.95,
      trust: 0.9,
      attention: 0.65,
      cardinality: 0.3,
      precision: 0.7,
      formStability: 0.95,
    }),
  },
];

/** Annual hours the mechanic could remove across the whole company. */
export function annualHoursSaved(s: Scenario): number {
  const people = roles[s.role].headcount * s.populationShare;
  const minutes = people * s.runsPerYear * s.minutesPerRun * s.removableShare;
  return minutes / 60;
}

export function affectedPeople(s: Scenario): number {
  return Math.round(roles[s.role].headcount * s.populationShare);
}
